name: Update README

on:
  push:
    branches:
      - main # Chỉ chạy khi có push lên nhánh main
  schedule:
    - cron: '0 * * * *' # Chạy mỗi giờ

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update README
      run: |
        # Lệnh để cập nhật README của bạn, ví dụ: cập nhật số lượng stars, visitors, v.v.
        # Bạn có thể sử dụng một script hoặc lệnh shell để thực hiện việc này
        ./update-readme.sh

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "docs: update README"
        git push
